[workspace]
resolver = "3"
members = [
    "cuddld",
    "cuddld_ar",
    "cuddld_diagnostics",
    "cuddld_elf",
    "cuddld_error",
    "cuddld_macros",
    "cuddld_macros_quote",
    "cuddld_pkg_config",
    "cuddld_test_harness",
    "cuddld_utils",
]

[workspace.package]
version = "0.0.0"
edition = "2024"

[workspace.dependencies]
cuddld_ar = { path = "cuddld_ar" }
cuddld_diagnostics = { path = "cuddld_diagnostics" }
cuddld_elf = { path = "cuddld_elf" }
cuddld_error = { path = "cuddld_error" }
cuddld_macros = { path = "cuddld_macros" }
cuddld_macros_quote = { path = "cuddld_macros_quote" }
cuddld_pkg_config = { path = "cuddld_pkg_config"}
cuddld_test_harness = { path = "cuddld_test_harness" }
cuddld_utils = { path = "cuddld_utils" }

[workspace.lints.clippy]
new_without_default = "allow"
len_without_is_empty = "allow"
