[package]
name = "plinky_pkg_config"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[[test]]
name = "pkgtest"
path = "pkgtest/harness.rs"
harness = false

[dependencies]
plinky_macros.workspace = true

[dev-dependencies]
plinky_error.workspace = true
plinky_test_harness.workspace = true
plinky_utils.workspace = true
