[package]
name = "plinky_elf"
edition.workspace = true
version.workspace = true

[lints]
workspace = true

[[test]]
name = "elftest"
path = "elftest/harness.rs"
harness = false

[dependencies]
plinky_diagnostics.workspace = true
plinky_macros.workspace = true
plinky_utils.workspace = true

[dev-dependencies]
plinky_error.workspace = true
plinky_test_harness.workspace = true
